### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by fuhrmannb** [mdonoughe/obs-gpmdp#1]
Hi. First of all, thx for your plugin, it works very well!

Currently, only left text alignment works. If song changes, text is reset without taking into account alignment settings. Can this settings be managed in the plugin?

**Comment by mdonoughe** [comment]
I think I know what you're seeing. There are two ways of aligning the text in the Now Playing source.

The text alignment setting in the source properties aligns lines of text relative to each other when you have a multi-line template. If you have a single-line template it doesn't really do anything.

The transform alignment (right click on the source, Transform→Edit Transform: Positional Alignment) determines how OBS positions the source on screen as it changes sizes (basically how it places the red box that appears when you select the source). There are more options here that allow you to do things like center the text within a larger box or make it fit a certain size or something like that.

![obs64_2018-08-10_21-56-32](https://user-images.githubusercontent.com/17961/43987175-c9bd409e-9cea-11e8-89d7-00122119e241.png)

If you want your text right aligned on the screen you probably want to set the transform alignment and likely also the text alignment. This way the ends of your lines match up and they stay the same distance from the right edge of the screen even when the text changes.

**Comment by fuhrmannb** [comment]
Indeed, that is a little tricky but it works! Thx for the tip, I close this issue.
