### ISSUE TITLE
New OBS Update seems to have broken this plugin

### ISSUE THREAD

**Issue by Vanteil** [mdonoughe/obs-gpmdp#3]
Since OBS 26.0.2 the plugin has not worked anymore. I have used the plugin with youtube music desktop player and it has worked just fine until now.

**Comment by mdonoughe** [comment]
Does it work if you go back to an older version of OBS or if you select Google Play Music? The GPMDP API is not working for me when I have YouTube selected (It says I am listening to `{"title":null,"artist":null,"album":null,"albumArt":null}`). If I use Google Play Music the OBS plugin works fine on 26.0.2.

**Comment by mdonoughe** [comment]
See MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3888

**Comment by Vanteil** [comment]
> 
> 
> See [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3888](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3888)

Thank you for the link! Seems like the issue is in the player itself then. I actually didn't notice the issue until I looked closer.
